### ISSUE TITLE
stuck at....5%

### ISSUE THREAD

**Issue by SeekPoint** [r0oth3x49/Tor#1]
G:\ub16_prj\Tor>python tor_services.py

----------------------------------------------------------------------------
 _____          ___                    ___              _
|_   _|__ _ _  | _ \_ _ _____ ___  _  / __| ___ _ ___ _(_)__ ___ ___
  | |/ _ \ '_| |  _/ '_/ _ \ \ / || | \__ \/ -_) '_\ V / / _/ -_|_-<
  |_|\___/_|   |_| |_| \___/_\_\_,  | |___/\___|_|  \_/|_\__\___/__/
                                |__/
                                       :-  by Nasir Khan (r0ot h3x49)
----------------------------------------------------------------------------

[*] Tor  :  0.3.2.10
[*] 0%   :  Starting
[*] 5%   :  Connecting to directory server

**Comment by r0oth3x49** [comment]
works fine for me can you might some issue with connecting to tor network on your ISP
